apiVersion: apps/v1
kind: Deployment
metadata:
  name: bottle-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bottle-app
  template:
    metadata:
      labels:
        app: bottle-app
    spec:
      containers:
        - name: bottle-app
          image: pyapp
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: bottle-app-service
spec:
  selector:
    app: bottle-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP

