name: Workflow Dispatch Demo

on:
  workflow_dispatch:
    inputs:
      MESSAGE:
        description: "Enter Message"
        required: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Workflow Dispatch demo
        env:
          MESSAGE: ${{ github.event.inputs.MESSAGE }}
        with:  
          run: |
            echo "${{ env.MESSAGE  }}"
